---
- name: Ensure that the pygpgme and yum-utils packages are installed
  tags: linuxhq
  become: true
  yum:
    name: "{{ item }}"
    state: present
  register: linuxhq_yum
  with_items:
    - pygpgme
    - yum-utils

- block:
    - name: Applying linuxhq repository configuration
      template:
        src: linuxhq.repo.j2
        dest: "/etc/yum.repos.d/linuxhq-{{ linuxhq_pkg }}.repo"
        owner: root
        group: root
        mode: 0644

    - name: Ensure that the linuxhq GPG keys are installed
      rpm_key:
        key: "https://packagecloud.io/linuxhq/{{ linuxhq_pkg }}/gpgkey"
        state: present
      register: linuxhq_rpm_key

    - name: Rebuilding cache for linuxhq-{{ linuxhq_pkg }} repository
      shell: |
        yum -y -q makecache \
            --disablerepo=* \
            --enablerepo=linuxhq-{{ linuxhq_pkg }}
      when: linuxhq_rpm_key|changed
  tags: linuxhq
  become: true
  when:
    - linuxhq_pkg is defined
    - linuxhq_yum|success 
...
