---
- name: Assert that variable prerequisites exist
  tags: linuxhq
  assert:
    that:
      - linuxhq_pkg is defined

- name: Ensure that the pygpgme and yum-utils packages are installed
  tags: linuxhq
  become: true
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - pygpgme
    - yum-utils

- name: Attempting to overlay linuxhq-{{ linuxhq_pkg }} repository configuration
  tags: linuxhq
  become: true
  template:
    src: linuxhq.repo.j2
    dest: "/etc/yum.repos.d/linuxhq-{{ linuxhq_pkg }}.repo"
    owner: root
    group: root
    mode: 0644

- name: Ensure that the linuxhq GPG keys are installed
  tags: linuxhq
  become: true
  rpm_key:
    key: "https://packagecloud.io/linuxhq/{{ linuxhq_pkg }}/gpgkey"
    state: present

- name: Rebuilding cache for linuxhq-{{ linuxhq_pkg }} repository
  tags: linuxhq
  become: true
  args:
    warn: no
  shell: |
    yum -y -q makecache \
        --disablerepo=* \
        --enablerepo=linuxhq-{{ linuxhq_pkg }}
...
